name: pangolin
description: The Desktop Environment for dahliaOS
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  utopia_wm:
    #path: ../utopia/
    git:
      url: https://github.com/dahliaOS/utopia.git
      ref: utopia

  provider: ^6.0.1
  animations: ^2.0.0-nullsafety.0
  easy_localization: ^3.0.0
  recase: ^4.0.0-nullsafety.0
  xml: ^5.3.0
  intl: ^0.17.0
  cached_network_image: ^3.0.0-nullsafety
  hive_flutter: any
  calculator:
    git:
      url: https://github.com/dahliaOS/calculator.git
  graft:
    git:
      url: https://github.com/dahliaOS/graft.git
  text_editor:
    git:
      url: https://github.com/dahliaOS/text_editor.git
  files:
    git:
      url: https://github.com/dahliaOS/files.git
      ref: old-base
  web_browser:
    git:
      url: https://github.com/dahliaOS/web_browser.git
  task_manager:
    git:
      url: https://github.com/dahliaOS/task_manager.git
  media:
    git:
      url: https://github.com/dahliaOS/media.git
  dahlia_clock:
    git:
      url: https://github.com/dahliaOS/clock.git
  system_logs:
    git:
      url: https://github.com/dahliaOS/system_logs.git
  terminal:
    git:
      url: https://github.com/dahliaOS/terminal.git
      ref: v2
  welcome:
    git:
      url: https://github.com/dahliaOS/welcome.git
  http: ^0.13.1

  # Icon Packs
  fluentui_system_icons:  ^1.1.143
  unicons: ^2.0.2
  battery_plus: ^2.0.1
  flutter_lints: ^1.0.4 

dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  integration_test:
#    sdk: flutter

dependency_overrides:
  material_design_icons_flutter: ^5.0.6295


flutter:
  uses-material-design: true

  assets:
    - assets/images/wallpapers/
    - assets/images/logos/
    - assets/images/other/
    - assets/icons/
    - assets/locales/
    - assets/json/visualData.json
    - assets/textures/
    - assets/fonts/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: DM-Sans
      fonts:
        - asset: assets/fonts/dm-sans/DMSans-Bold.ttf
        - asset: assets/fonts/dm-sans/DMSans-BoldItalic.ttf
        - asset: assets/fonts/dm-sans/DMSans-Italic.ttf
        - asset: assets/fonts/dm-sans/DMSans-Medium.ttf
        - asset: assets/fonts/dm-sans/DMSans-MediumItalic.ttf
        - asset: assets/fonts/dm-sans/DMSans-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Black.ttf
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
        - asset: assets/fonts/lato/Lato-Bold.ttf
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
        - asset: assets/fonts/lato/Lato-Italic.ttf
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-Light.ttf
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
        - asset: assets/fonts/lato/Lato-Thin.ttf
        - asset: assets/fonts/lato/Lato-Italic.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
    - family: FiraCode
      fonts:
       - asset: assets/fonts/firacode/FiraCode-Bold.ttf
       - asset: assets/fonts/firacode/FiraCode-Medium.ttf
       - asset: assets/fonts/firacode/FiraCode-Retina.ttf
       - asset: assets/fonts/firacode/FiraCode-Light.ttf
