name: pangolin
description: The Desktop Environment for dahliaOS
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0-0 <4.0.0"

dependencies: 
  animations: ^2.0.7
  cached_network_image: ^3.2.0
  collection: ^1.17.1
  dahlia_shared:
    git: 
      url: https://github.com/dahliaOS/shared
      ref: main
  dbus: ^0.7.4
  diffutil_dart: ^3.0.0
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  gsettings: ^0.2.7
  http: ^0.13.5
  intl: ^0.18.0
  jovial_svg: ^1.1.5
  logging: ^1.0.2
  path: ^1.8.2
  pausable_timer: ^1.0.0+5
  provider: ^6.0.1
  shared_preferences: ^2.0.15
  stack_trace: ^1.11.0
  upower: ^0.7.0
  url_launcher: ^6.1.3
  utopia_wm: 
    git: 
      url: https://github.com/dahliaOS/utopia.git
      ref: utopia
  uuid: ^3.0.7
  xdg_desktop: 
    git: https://github.com/HrX03/xdg.dart
  xdg_directories: ^1.0.1
  yatl: 
    git: 
      url: https://github.com/HrX03/yatl
      path: yatl
  yatl_flutter: 
    git: 
      url: https://github.com/HrX03/yatl
      path: yatl_flutter
  yatl_gen: 
    git: 
      url: https://github.com/HrX03/yatl
      path: yatl_gen
  zenit_ui: 
    git: 
      url: https://github.com/dahliaOS/zenit_ui.git
      # change before merge
      ref: v0.0.11


dev_dependencies: 
  build_runner: ^2.4.4
  lint: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/logos/
    - assets/images/other/
    - assets/images/wallpapers/
    - assets/textures/
    - assets/fonts/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf