name: GeneratedApp
description: A generated Flutter project.

dependencies:
  intl: ^0.16.1
  expressions: ^0.1.2
  json_annotation: ^2.0.0
  shared_preferences: ^0.5.7+3
  provider: ^4.1.2
  flutter_localizations:
    sdk: flutter
  hive: ^1.4.1+1
  path_provider: ^1.6.11
#Useful in an ideal future but not now.  random_color: ^1.0.5

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
# application.json handles all applications and must not be deleted.
flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Source Code pro
      fonts:
        - asset: fonts/Source_Code_Pro/SourceCodePro-ExtraLight.ttf
          weight: 100
        - asset: fonts/Source_Code_Pro/SourceCodePro-ExtraLightItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-Light.ttf
          weight: 300
        - asset: fonts/Source_Code_Pro/SourceCodePro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-Regular.ttf
          weight: 400
        - asset: fonts/Source_Code_Pro/SourceCodePro-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-Medium.ttf
          weight: 500
        - asset: fonts/Source_Code_Pro/SourceCodePro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-SemiBold.ttf
          weight: 700
        - asset: fonts/Source_Code_Pro/SourceCodePro-SemiBoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-Bold.ttf
          weight: 900
        - asset: fonts/Source_Code_Pro/SourceCodePro-BoldItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-Black.ttf
          weight: 900
        - asset: fonts/Source_Code_Pro/SourceCodePro-BlackItalic.ttf
          weight: 900
          style: italic
  assets:
  - lib/application.json
  - lib/images/
  - lib/images/Desktop/Dahlia/dahlia_material_background.jpg
  - lib/images/Desktop/Dahlia/forest.jpg
  - lib/images/Desktop/Cityscapes/stairs.png
  - lib/images/icons/v2/compiled/
  - lib/images/logo-color.png
  - lib/images/dahlia.png
  - lib/localization/languages/de.json
  - lib/localization/languages/en.json