name: GeneratedApp
description: A generated Flutter project.

dependencies:
  intl: ^0.15.7
  expressions: ^0.1.2
  json_annotation: ^2.0.0
  shared_preferences: ^0.5.7+3
  provider: ^4.1.2
  random_color: ^1.0.5

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
# application.json handles all applications and must not be deleted.
flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Source Code pro
      fonts:
        - asset: fonts/Source_Code_Pro/SourceCodePro-ExtraLight.ttf
          weight: 100
        - asset: fonts/Source_Code_Pro/SourceCodePro-ExtraLightItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-Light.ttf
          weight: 300
        - asset: fonts/Source_Code_Pro/SourceCodePro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-Regular.ttf
          weight: 400
        - asset: fonts/Source_Code_Pro/SourceCodePro-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-Medium.ttf
          weight: 500
        - asset: fonts/Source_Code_Pro/SourceCodePro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-SemiBold.ttf
          weight: 700
        - asset: fonts/Source_Code_Pro/SourceCodePro-SemiBoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-Bold.ttf
          weight: 900
        - asset: fonts/Source_Code_Pro/SourceCodePro-BoldItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-Black.ttf
          weight: 900
        - asset: fonts/Source_Code_Pro/SourceCodePro-BlackItalic.ttf
          weight: 900
          style: italic
  assets:
  - lib/application.json
  - lib/images/def.png
  - lib/images/menu.png
  - lib/images/wallpaper.png
  - lib/images/google_logo.png
  - lib/images/Gmail-icon.png
  - lib/images/phone.png
  - lib/images/calc.png
  - lib/images/music.png
  - lib/images/settings.png
  - lib/images/clock.png
  - lib/images/Desktop/Dahlia/dahlia_material_background.jpg
  - lib/images/Desktop/Dahlia/forest.jpg
  - lib/images/Desktop/Cityscapes/stairs.png
  - lib/images/icons/v2/compiled/terminal.png
  - lib/images/icons/v2/compiled/task.png
  - lib/images/icons/v2/compiled/settings.png
  - lib/images/icons/v2/compiled/root.png
  - lib/images/icons/v2/compiled/notes.png
  - lib/images/icons/v2/compiled/note_mobile.png
  - lib/images/icons/v2/compiled/logs.png
  - lib/images/icons/v2/compiled/files.png
  - lib/images/icons/v2/compiled/disks.png
  - lib/images/icons/v2/compiled/calculator.png
  - lib/images/icons/v2/compiled/android.png
  - lib/images/icons/v2/compiled/theme.png