name: Build Linux
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.xml'
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - uses: subosito/flutter-action@v1
        name: Set up Flutter
      - run: flutter channel beta
        name: Switch Flutter channel
      - run: flutter config --enable-linux-desktop
        name: Enable linux support
      - run: sudo apt update && sudo apt install cmake ninja-build clang libgtk-3-dev -y
        name: Install system dependencies
      - name: Get dependencies
        run: flutter pub get
      - name: Generate Localization
        run: dart bin/locale_gen.dart assets/locales lib/internal/locales
      - run: flutter build linux --debug --no-sound-null-safety
        name: Build Pangolin for Linux
      - name: Upload linux build
        uses: actions/upload-artifact@v2
        with:
          name: pangolin-linux-builds
          path: build/linux/debug/pangolin_desktop
