name: CI
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter channel master
      - run: flutter config --enable-linux-desktop
      - run: sudo apt update && sudo apt install cmake ninja-build clang libgtk-3-dev -y
      - run: flutter build linux --debug
      - name: Upload linux build for build_linux
        uses: actions/upload-artifact@v2
        with:
          name: pangolin-linux-builds
          path: build/linux/debug/pangolin_desktop
  build_and_deploy_web:
    name: Build and Deploy Web
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - uses: subosito/flutter-action@v1
    - run: flutter channel master
    - run: flutter config --enable-web
    - run: flutter build web
    - name: Prepare to deploy
      run: git config --global user.name "dahliaOS" && git commit -a -m "You've found me!"
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{secrets.FTP_HOST}}/public_html/web_build
        ftp-username: ${{secrets.FTP_USERNAME}}
        ftp-password: ${{secrets.FTP_PASSWORD}}
        local-dir: build/web/