
name: Build and Deploy to Web

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - uses: subosito/flutter-action@v1
        name: Set up Flutter
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Switch Flutter channel
        run: flutter channel master
      - name: Make sure Flutter is up to date
        run: flutter upgrade
      - name: Enable Web support
        run: flutter config --enable-web
      - name: Install system dependencies
        run: sudo apt update && sudo apt install cmake ninja-build clang libgtk-3-dev util-linux liblzma-dev libgcrypt-dev jpegoptim optipng -y
      - name: Get dependencies
        run: flutter pub get && flutter pub upgrade
      - name: Build Pangolin for Web
        run: flutter build web --release
      - name: Deploy to GitHub pages
        run: |
          echo "web.dahliaos.io" >> build/web/CNAME
          jpegoptim --size=500k build/web/assets/assets/images/wallpapers/*.jpg
          optipng -force -strip all -silent build/web/assets/assets/images/wallpapers/*.png
          git config user.name github-actions
          git config user.email "action@github.com"
          git --work-tree build/web add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin HEAD:gh-pages --force
